### ISSUE TITLE
Add exclude for valid-params rule

### ISSUE THREAD

**Issue by alexilyaev** [eslint-community/eslint-plugin-promise#127]
### Description

When using Bluebird, there are cases that deviate from the standard usage of promise functions.  
One that I found is Bluebird's `.catch` can receive 2 arguments.  
See http://bluebirdjs.com/docs/api/catch.html#filtered-catch

So, I think we should have an exclude option to set which functions not to check.

**Comment by macklinu** [comment]
I'd be open to a PR for this!
