### ISSUE TITLE
Cannot read property 'replace' of undefined Use --force to continue.

### ISSUE THREAD

**Issue by phani17c** [eslint-community/eslint-plugin-promise#156]
### Description

Warning: Cannot read property 'replace' of undefined Use --force to continue.
When I am adding "promise/no-callback-in-promise": "error",getting the above error

### Versions

- Node version: 8.0.0
- ESLint version:"5.12.0"
- eslint-plugin-promise version: "4.0.1"

**Comment by xjamundx** [comment]
What does your code look like?

**Comment by ota-meshi** [comment]
I don't seem to have enough information to reproduce the problem. So I will close this issue.
