### ISSUE TITLE
400 response when trying to install 

### ISSUE THREAD

**Issue by MattGoldwater** [eslint-community/eslint-plugin-promise#164]
I've been getting a 400 error when trying to install the plugin. Not sure if this would be a problem with the repo or NPM.

npm install eslint-plugin-promise --save-dev
npm WARN @imp-platform/imp-nextgen-dashboard@1.2.0 No repository field.

npm ERR! code E400
npm ERR! 400 Bad Request: eslint-plugin-promise@^4.1.1

**Comment by TheDutchCoder** [comment]
I can confirm this as well, seems like npm refuses to install the 5+ version.

**Comment by MichaelDeBoey** [comment]
Closing this issue as installing the package is working
