### ISSUE TITLE
🤖 integrate all-contributors bot

### ISSUE THREAD

**Issue by iamdarshshah** [eslint-community/eslint-plugin-promise#211]
### Description

It's a feature that will help in keeping track of contributions made by the contributors and list them in the readme. This all will be handled by [all-contributors](https://allcontributors.org/) bot that needs to be integrated into this repo.

**It will look similar to this:**
![Capture](https://user-images.githubusercontent.com/25670841/107609374-ba1e2800-6c64-11eb-8550-0b112a296347.PNG)

### Steps to integrate it:
- [ ] Install all-contributors bot to this repo - [docs](https://allcontributors.org/docs/en/bot/installation) [@xjamundx to update]
- [ ] Configure all-contributors bot - [@iamdarshshah to update (Will raise PR for the same)]

@xjamundx & @macklinu - What're your suggestions?

> We're open to knowing your thoughts on this. Any ideas/suggestions/feedbacks are much appreciated. 🙂

**Comment by voxpelli** [comment]
PR welcome, but will close for now as it's not something that other `eslint-community` projects has yet. But I do agree it can be nice 👍
