### ISSUE TITLE
There is no documentation for some rules

### ISSUE THREAD

**Issue by MansurAliKoroglu** [eslint-community/eslint-plugin-promise#214]
### Description

Four of the rules has no documentation.

### Steps to Reproduce

1. Visit the links:
- https://github.com/xjamundx/eslint-plugin-promise/blob/HEAD/docs/rules/no-promise-in-callback.md
- ~~https://github.com/xjamundx/eslint-plugin-promise/blob/HEAD/docs/rules/no-callback-in-promise.md~~
- https://github.com/xjamundx/eslint-plugin-promise/blob/HEAD/docs/rules/avoid-new.md
- ~~https://github.com/xjamundx/eslint-plugin-promise/blob/HEAD/docs/rules/prefer-await-to-callbacks.md~~

**Comment by xjamundx** [comment]
Partially addressed in #215

**Comment by DerZyklop** [comment]
Related discussion about the reasons for `avoid-new`: https://github.com/eslint-community/eslint-plugin-promise/issues/111

**Comment by DamienCassou** [comment]
I agree that rules should be documented.
