### ISSUE TITLE
no-callback-in-promise use cases

### ISSUE THREAD

**Issue by xjamundx** [eslint-community/eslint-plugin-promise#220]
It has been requested that we support these use cases in the `no-callback-in-promise` rule
```
    // TODO: support safe callbacks
    // 'whatever.then((err) => { process.nextTick(() => cb()) })',
    // 'whatever.then((err) => { setImmediate(() => cb())) })',
    // 'whatever.then((err) => setImmediate(() => cb()))',
    // 'whatever.then((err) => process.nextTick(() => cb()))',
    // 'whatever.then((err) => process.nextTick(cb))',
    // 'whatever.then((err) => setImmediate(cb))',
```

**Comment by Sandesh333333** [comment]
> It has been requested that we support these use cases in the `no-callback-in-promise` rule
> 
> ```
>     // TODO: support safe callbacks
>     // 'whatever.then((err) => { process.nextTick(() => cb()) })',
>     // 'whatever.then((err) => { setImmediate(() => cb())) })',
>     // 'whatever.then((err) => setImmediate(() => cb()))',
>     // 'whatever.then((err) => process.nextTick(() => cb()))',
>     // 'whatever.then((err) => process.nextTick(cb))',
>     // 'whatever.then((err) => setImmediate(cb))',
> ```

**Comment by jack828** [comment]
This is exactly what the documentation recommends.

https://github.com/xjamundx/eslint-plugin-promise/blob/development/docs/rules/no-callback-in-promise.md
