### ISSUE TITLE
`promise/prefer-await-to-then` ignore constructor scope

### ISSUE THREAD

**Issue by dimaMachina** [eslint-community/eslint-plugin-promise#436]
### Description

`promise/prefer-await-to-then` should not report errors if `.then`/`.catch` calls are inside constructor of some class

Because we can't have `async constructor`

**Comment by yacinehmito** [comment]
You could always define an `async` function and call that function in the constructor without awaiting.

**Comment by brettz9** [comment]
While I think this could be done with configuration, I think some projects may prefer to avoid such usages in case there is something wrong with using Promises at all in a constructor.
