### ISSUE TITLE
does it support typescript?

### ISSUE THREAD

**Issue by zzzgit** [eslint-community/eslint-plugin-promise#447]
does it support typescript?

**Comment by voxpelli** [comment]
If you use typescript-eslint, then yes

**Comment by brettz9** [comment]
@voxpelli I wonder if this is asking for type declaration files now that flat configs are supported...

**Comment by voxpelli** [comment]
@brettz9 Good thinking, we should add an issue for that (do you want to do that?)

Generating it from JS should be easy, I do it in eg `neostandard`

**Comment by brettz9** [comment]
Added #488.
