### ISSUE TITLE
Support ESLint 9 and Flat config

### ISSUE THREAD

**Issue by brettz9** [eslint-community/eslint-plugin-promise#449]
### Description

Please add support for ESLint 9, including Flat config support.

See:

1. https://eslint.org/docs/latest/use/configure/configuration-files-new
1. https://eslint.org/blog/2022/08/new-config-system-part-1/
1. https://eslint.org/blog/2022/08/new-config-system-part-2/
1. https://eslint.org/docs/latest/use/configure/migration-guide

Thanks!

**Comment by erichosick** [comment]
Want to try and work on this a bit. Trying to follow the pattern in [eslint-plugin-n](https://github.com/eslint-community/eslint-plugin-n/blob/fc77da2a0c3fc3720521f09bd6ca0aa196868ad2/lib/index.js#L52)

```
import promise from 'eslint-plugin-promise';

/// TODO: Get the package name and version from package.json
const mod = {
  meta: {
    name: 'eslint-plugin-promise', /// pkg.name,
    version: '6.1.1', /// pkg.version,
  },
  rules: promise.rules, /// the rule definitions
}

const recommendedConfig = {
  flat: {
    languageOptions: {}, /// no language options for promise that I know of
    rules: promise.configs.recommended.rules, /// the rules we are applying
  }
}

/// really not sure how the eslint-plugin-promise wants to expose their
/// but here is a sort of guess.
mod.configs = {
  "flat/recommended": [
    {
      plugins: {
        promise: mod
      },
      files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
      ...recommendedConfig.flat
    },
  ],
}

export default mod;
```

usage in flat file is something like:

```
// files: eslint.config.mjs

import promise from './eslint-plugin-promise-flat.mjs';
const flatConfig = promise.configs["flat/recommended"];

const eslintConfigObjects = [
  ...flatConfig,
];

export default eslintConfigObjects;
```

but when actually linting say `no-promise-in-callback`, `getAncestors` is undefined.

The line of code is [here](https://github.com/eslint-community/eslint-plugin-promise/blob/bbcfcbf85ef97cba58f4fe4b9f46c907e04bc5a6/rules/no-promise-in-callback.js#L33).

So, not quite sure why this is happening.

**Comment by brettz9** [comment]
Some of the APIs have been dropped in ESLint 9. `context.getAncestors` should be changed to `SourceCode#getAncestors(node)`. See https://eslint.org/docs/latest/extend/custom-rules for the already deprecated items which are being dropped in ESLint 9.

**Comment by erichosick** [comment]
Heads up that the above link sends us to the older docs (at this time). Maybe this link instead? https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getancestors()

**Comment by brettz9** [comment]
Sure, I just meant the older docs for the fact that it had already been deprecated and a replacement was indicated there too. But yours is presumably even more current.

**Comment by erichosick** [comment]
Just one more note that the above example code does work for eslint v8. So, may be helpful for anyone wanting to use flat config in V8.

**Comment by TheElegantCoding** [comment]
+1 to this support

**Comment by doberkofler** [comment]
eslint v9 has just been released and support for v9 would be greatly appreciated

**Comment by voxpelli** [comment]
I'll try to find to implement this if no-one beats me to it :+1:

**Comment by crystalfp** [comment]
FYI. The rules that I had to disable to have eslint succeed are:
```
        "promise/no-return-wrap": "warn",
        "promise/no-promise-in-callback": "warn",
        "promise/no-nesting": "warn",
        "promise/no-callback-in-promise": "warn",
```

**Comment by voxpelli** [comment]
> Hi guys, are there any plans to support flat config?

Yes, just not a definite timeline

**Comment by TheElegantCoding** [comment]
the package also need type declaration for the export in flat config 
![image](https://github.com/eslint-community/eslint-plugin-promise/assets/70770072/f389b914-f16a-4e6e-9749-ef30ce2887b0)

**Comment by donalmurtagh** [comment]
It's possible to make the current version of the plugin promise work in a ESLint v9 flag configuration file using `@eslint/compat` by following [these instructions](https://eslint.org/blog/2024/05/eslint-compatibility-utilities/).

In my case I made these changes to `eslint.config.js`

```javascript
import { FlatCompat } from '@eslint/eslintrc'
import { fixupConfigRules } from '@eslint/compat'

const compat = new FlatCompat()

export default [
  /*
  To make the promise plugin work with ESLint v9 we have to use
  1. fixupConfigRules to fix obsolete rules API usages https://eslint.org/blog/2024/05/eslint-compatibility-utilities/
  2. FlatCompat to convert the plugin's config format to the v9 flat format
  */
  ...fixupConfigRules(
    compat.config({
      extends: ['plugin:promise/recommended'],
      // Ignore the E2E tests because the Cypress API includes a then() which the plugin erroneously identifies
      // as a call on a promise
      ignorePatterns: ['tests/e2e']
    })
  ),
  // other config objects
]
```

**Comment by zloirock** [comment]
https://github.com/eslint-community/eslint-plugin-promise/issues/472

**Comment by mightyiam** [comment]
Thank you!
