### ISSUE TITLE
Swap release process to release-please

### ISSUE THREAD

**Issue by voxpelli** [eslint-community/eslint-plugin-promise#506]
I would personally be in favor of switching to a release please flow, like in https://github.com/eslint-community/eslint-plugin-n/pull/305, as that catches errors like this before release

This would help catch release errors like https://github.com/eslint-community/eslint-plugin-promise/issues/484#issuecomment-2247374199 before they actually get released

**Comment by voxpelli** [comment]
Thoughts @scagood @aladdin-add @brettz9?

**Comment by brettz9** [comment]
Looks all right to me...

**Comment by scagood** [comment]
I do much prefer release-please as:
1. It allows you to see the change logs in the PR description
2. The package version is always correct in the package.json
3. It allows for a more transparent release process

(Also, its just personal comfort :joy:)

---

It does have some down sides, such as merge commits occasionally create double entries in the change log.

**Comment by ota-meshi** [comment]
Between `release-please` and `semantic-release`, I personally prefer `release-please`. Because we can control the release timing.

**Comment by voxpelli** [comment]
> It does have some down sides, such as merge commits occasionally create double entries in the change log.

Yeah, one should preferably only do squash (or rebase commits) with it

**Comment by ota-meshi** [comment]
Currently, it appears that only `squash merging` is allowed for this repository.
