### ISSUE TITLE
catch-or-return options to report `then(a, b)` or `then(null, b)`

### ISSUE THREAD

**Issue by Jessidhia** [eslint-community/eslint-plugin-promise#52]
`makePromise().then(thenHandler, catchHandler)` is incorrectly considered correct by the always-catch plugin when `allowThen: true` is specified.

While the `catchHandler` will handle a rejection of the `Promise` returned by `makePromise()`, it will _not_ handle any rejection that happens in the `thenHandler`; it needs to be handled by its own catch handler, which could be a `.then(null /* | undefined */, catchHandler)` according to `allowThen: true`.

**Comment by xjamundx** [comment]
I believe that the current behavior is correct as some people would rather do without `catch` or a second `then` altogether.

I see your point that they are going to be missing any crashes in the initial handler. I'd consider an `allowThenStrict` or something 🤔

**Comment by okcoker** [comment]
> I'd consider an allowThenStrict or something

Would this disallow the second argument being used within `.then()` altogether? I'm all for having that as I don't think that's currently possible right?

**Comment by brettz9** [comment]
I think we may need `allowThenStrict` (to err on `then(a, b)` but pass for `then(null, b)`) and `preventThenRejectHandler` (which errs on both forms) as separate options.

**Comment by brettz9** [comment]
Maybe it is better for these options to be their own rule (and as might be tracked by #217).
