### ISSUE TITLE
Access to `Promise.prototype.%somethingStandard%` trigger `promise/spec-only`

### ISSUE THREAD

**Issue by zloirock** [eslint-community/eslint-plugin-promise#533]
```
x:y  error  Avoid using non-standard 'Promise.prototype'  promise/spec-only
```

**Comment by voxpelli** [comment]
Why are you accessing `Promise.prototype`? 🤔

**Comment by zloirock** [comment]
It's a very strange question.

At first, because methods like `.catch` and `.finally` are generics and can be applied on non-native promises. At second, for caching for avoiding unneeded observable side effects, for preventing breakage in case of patching, etc. I have **many** other reasons to get access to methods from `Promise.prototype`.
